import Head from "next/head";
import estilos from "@/styles/Home.module.css";
import Topo from "@/components/Topo"
import Capa from "@/components/Capa"
import Produtos from "@/components/Produtos";

export default function Home() {
  return (
    <>
      <Head>
        <title>Staine Cosméticos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Topo />
      <section>
        <Capa />
        <Produtos />
      </section>
    </>
  );
}
